# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kkpHilyzU9s1FKbU2BUs1KbsakSO1EUf
"""

# Install necessary libraries (if not already present)
!pip install pandas numpy scikit-learn torch matplotlib

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import torch

# 1. Load the Dataset
try:
    df = pd.read_csv('/content/delhi-weather-aqi-2025.csv')
    print("Dataset loaded successfully.")
except FileNotFoundError:
    print("File not found. Please check the file path in the left sidebar.")

# 2. Basic Cleaning
# Combine date and time to create a proper Datetime index
# We add dayfirst=True because your dates are in DD/MM/YYYY format (e.g., 13/01/2025)
df['datetime'] = pd.to_datetime(df['date_ist'] + ' ' + df['time_ist'], dayfirst=True)
df = df.sort_values(['location', 'datetime'])

# 3. Feature Engineering
# Pollution is cyclical. We need to tell the model "what time of day" and "what day of year" it is.
df['hour'] = df['datetime'].dt.hour
df['month'] = df['datetime'].dt.month
df['day_of_week'] = df['datetime'].dt.dayofweek

# 4. Lag Features (Physics: Persistence)
# Pollution now depends on pollution 1 hour ago.
df['pm2_5_lag1'] = df.groupby('location')['pm2_5'].shift(1)
df['pm2_5_lag24'] = df.groupby('location')['pm2_5'].shift(24) # Same hour yesterday

# Drop rows created by lagging (NaN values)
df = df.dropna()

# 5. Select Features for Model
features = ['temp_c', 'humidity', 'pressure_mb', 'windspeed_kph',
            'hour', 'month', 'pm2_5_lag1', 'pm2_5_lag24']
target = 'pm2_5'

# Normalize Data (Deep Learning requires 0-1 scale)
scaler_x = MinMaxScaler()
scaler_y = MinMaxScaler()

# Fit scalers on the data
X_data = scaler_x.fit_transform(df[features])
y_data = scaler_y.fit_transform(df[[target]])

# 6. Create Sequences (Time Windows)
# The model looks back 12 hours to predict the next hour.
def create_sequences(X, y, time_steps=12):
    Xs, ys = [], []
    for i in range(len(X) - time_steps):
        Xs.append(X[i:(i + time_steps)])
        ys.append(y[i + time_steps])
    return np.array(Xs), np.array(ys)

TIME_STEPS = 12
X_seq, y_seq = create_sequences(X_data, y_data, TIME_STEPS)

# Convert to PyTorch Tensors
X_tensor = torch.tensor(X_seq, dtype=torch.float32).to(device)
y_tensor = torch.tensor(y_seq, dtype=torch.float32).to(device)

print(f"Data Preprocessing Complete.")
print(f"Input Shape: {X_tensor.shape}")
# Should be [Samples, 12 (Hours), 8 (Features)]

import torch.nn as nn

class PollutionLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, output_size):
        super(PollutionLSTM, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers

        # The LSTM layer
        # input_size = 8 (number of features)
        # hidden_size = 64 (internal memory size)
        # num_layers = 2 (depth of the network)
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True, dropout=0.2)

        # Fully connected layer to map hidden state to output (PM2.5)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        # Initialize hidden state and cell state with zeros
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device)
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size).to(device)

        # Forward propagation through LSTM
        # out shape: (batch_size, seq_length, hidden_size)
        out, _ = self.lstm(x, (h0, c0))

        # Decode the hidden state of the last time step
        # We only care about the output of the last hour in the sequence to predict the next hour
        out = self.fc(out[:, -1, :])
        return out

# --- Physics-Informed Loss Function ---
def physics_loss(pred, target, inputs):
    # 1. Standard Mean Squared Error (Data Fidelity)
    # This forces the model to match the actual sensor readings
    mse_loss = nn.MSELoss()(pred, target)

    # 2. Physical Constraint: Wind Dispersion Logic
    # inputs shape: [Batch, 12, 8]
    # Feature index 3 is 'windspeed_kph'
    # Feature index 6 is 'pm2_5_lag1' (previous pollution)

    wind_norm = inputs[:, -1, 3]     # Get wind speed of the last time step
    prev_pollution = inputs[:, -1, 6] # Get pollution of the last time step

    # PHYSICS HYPOTHESIS:
    # If wind is strong (>0.5 normalized, approx >10km/h),
    # pollution should not increase drastically.
    # We penalize the model if it predicts an increase when wind is high.

    diff = pred.squeeze() - prev_pollution # Change in pollution
    penalty = torch.mean(torch.relu(diff) * wind_norm)

    # Total Loss = Data Fit + Physics Constraint
    total_loss = mse_loss + 0.05 * penalty
    return total_loss, mse_loss, penalty

# Initialize Model Parameters
input_dim = 8      # Number of features
hidden_dim = 64    # Number of neurons in hidden layer
layer_dim = 2      # Number of LSTM layers
output_dim = 1     # Predicting a single value (PM2.5)

model = PollutionLSTM(input_dim, hidden_dim, layer_dim, output_dim).to(device)

# Define Optimizer
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

print("Model Architecture Defined.")
print(model)

import torch.utils.data as data_utils

# 1. Prepare Data Loaders
# Batch size defines how many samples the model sees at once
batch_size = 64

dataset = data_utils.TensorDataset(X_tensor, y_tensor)
loader = data_utils.DataLoader(dataset, batch_size=batch_size, shuffle=True)

# 2. Training Loop
num_epochs = 30 # Number of times the model sees the entire dataset

print("Starting Training...")
loss_history = []

for epoch in range(num_epochs):
    model.train() # Set model to training mode

    epoch_loss = 0
    epoch_mse = 0
    epoch_phys = 0

    for X_batch, y_batch in loader:
        # Move batch to GPU
        X_batch, y_batch = X_batch.to(device), y_batch.to(device)

        # Clear gradients from previous step
        optimizer.zero_grad()

        # Forward pass: Compute predicted output
        outputs = model(X_batch)

        # Compute Loss (MSE + Physics Penalty)
        loss, mse, phys = physics_loss(outputs, y_batch, X_batch)

        # Backward pass: Compute gradient of the loss w.r.t. model parameters
        loss.backward()

        # Update parameters
        optimizer.step()

        epoch_loss += loss.item()
        epoch_mse += mse.item()
        epoch_phys += phys.item()

    # Calculate average loss for the epoch
    avg_loss = epoch_loss / len(loader)
    avg_mse = epoch_mse / len(loader)
    avg_phys = epoch_phys / len(loader)

    loss_history.append(avg_loss)

    # Print progress every 5 epochs
    if (epoch+1) % 5 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Total Loss: {avg_loss:.6f}, MSE: {avg_mse:.6f}, Physics Penalty: {avg_phys:.6f}')

print("Training Complete!")

import matplotlib.pyplot as plt

# 1. Switch to Evaluation Mode
model.eval()

# 2. Make Predictions on the full dataset
with torch.no_grad():
    predictions = model(X_tensor)

# 3. Inverse Transform to get real PM2.5 values (µg/m³)
# We move tensors back to CPU for numpy operations
predictions_actual = scaler_y.inverse_transform(predictions.cpu().numpy())
y_actual = scaler_y.inverse_transform(y_tensor.cpu().numpy())

# 4. Plotting
plt.figure(figsize=(14, 7))

# Plot actual vs predicted for a slice of time (e.g., first 500 hours)
plt.plot(y_actual[:500], label='Actual PM2.5', color='blue', alpha=0.6)
plt.plot(predictions_actual[:500], label='Predicted PM2.5', color='red', linestyle='--')

plt.title('Delhi Air Quality Prediction: Actual vs Physics-Informed Model')
plt.xlabel('Time Steps (Hours)')
plt.ylabel('PM2.5 Concentration (µg/m³)')
plt.legend()
plt.grid(True)
plt.show()

# 5. Calculate RMSE (Root Mean Squared Error) in real units
rmse = np.sqrt(np.mean((predictions_actual - y_actual)**2))
print(f"Root Mean Squared Error (RMSE): {rmse:.2f} µg/m³")

print("\n--- Simulating Urban Planning Scenario ---")
print("Scenario: Traffic Reduction Policy (20% lower baseline emissions)")

# We simulate a 20% drop in the lagged pollution features (pm2_5_lag1, pm2_5_lag24)
# Note: In a real scenario, you would re-run the simulation step-by-step.
# Here we approximate by modifying the input features slightly.

# Create a copy of inputs
X_scenario = X_tensor.clone()

# Reduce pollution history features (indices 6 and 7) by 20%
# Feature 6: pm2_5_lag1, Feature 7: pm2_5_lag24
X_scenario[:, :, 6] *= 0.8
X_scenario[:, :, 7] *= 0.8

# Predict with modified inputs
with torch.no_grad():
    scenario_preds = model(X_scenario)
    scenario_actual = scaler_y.inverse_transform(scenario_preds.cpu().numpy())

# Compare average predicted pollution
current_avg = np.mean(y_actual)
scenario_avg = np.mean(scenario_actual)
reduction_pct = ((current_avg - scenario_avg) / current_avg) * 100

print(f"Current Average PM2.5: {current_avg:.2f} µg/m³")
print(f"Predicted Average under Scenario: {scenario_avg:.2f} µg/m³")
print(f"Estimated Reduction: {reduction_pct:.2f}%")

from sklearn.cluster import KMeans

# ==========================================
# PHASE 5: URBAN METABOLISM & PLANNING ENGINE
# ==========================================

print("--- Initializing Urban Metabolism Analysis ---")

# 1. Define Aggregated Features for each Location
# We analyze the 'metabolism' of each location by averaging its recent behavior
# FIX: Include 'lon' and 'lat' in the groupby to make them available for plotting
location_stats = df.groupby('location')[['temp_c', 'humidity', 'windspeed_kph', 'pm2_5', 'co', 'no2', 'lon', 'lat']].mean().reset_index()

# 2. Create "Urban Stress Index" (USI)
# Logic: High Pollution + High Temp + Low Wind = High Stress (Unhealthy Metabolism)
# We normalize these factors to create a 0-100 score.
# Note: We invert wind speed because low wind = higher stress.

# Normalize key parameters (0 to 1)
location_stats['stress_pollution'] = location_stats['pm2_5'] / location_stats['pm2_5'].max()
location_stats['stress_heat'] = location_stats['temp_c'] / location_stats['temp_c'].max()
location_stats['stress_stagnation'] = 1 - (location_stats['windspeed_kph'] / location_stats['windspeed_kph'].max()) # Inverse

# Calculate Composite Score (Weighted Average)
# We weight pollution highest as it's critical for health.
location_stats['urban_stress_index'] = (
    (location_stats['stress_pollution'] * 0.5) +
    (location_stats['stress_heat'] * 0.3) +
    (location_stats['stress_stagnation'] * 0.2)
) * 100

# 3. AI Clustering for Zoning (K-Means)
# We use AI to automatically group locations based on their characteristics
# Features for clustering: Temp, Wind, PM2.5, NO2 (Traffic proxy)
X_cluster = location_stats[['temp_c', 'windspeed_kph', 'pm2_5', 'no2']].values

# Initialize KMeans to find 3 types of zones
kmeans = KMeans(n_clusters=3, random_state=42)
location_stats['zone_type'] = kmeans.fit_predict(X_cluster)

# Define Zone Labels based on cluster centers logic
# (Logic: 0=Stagnant/HighPoll, 1=Moderate, 2=Ventilated or similar - adjusted by data)
cluster_map = {}
for i in range(3):
    center = kmeans.cluster_centers_[i]
    # Logic: High PM2.5 + Low Wind = Stagnation Zone
    if center[2] > location_stats['pm2_5'].mean() and center[1] < location_stats['windspeed_kph'].mean():
        cluster_map[i] = "Stagnation Zone (High Risk)"
    # Logic: High NO2 = Traffic Hotspot
    elif center[3] > location_stats['no2'].mean():
        cluster_map[i] = "Traffic Hotspot (Emission Source)"
    else:
        cluster_map[i] = "Ventilation Corridor (Lower Risk)"

location_stats['zone_label'] = location_stats['zone_type'].map(cluster_map)

# ==========================================
# OUTPUT: THE URBAN PLANNING REPORT
# ==========================================

print("\n" + "="*60)
print("URBAN METABOLISM REPORT: DELHI CITY ZONING")
print("="*60)

for index, row in location_stats.iterrows():
    print(f"\nLocation: {row['location']}")
    print(f"Zone Classification: {row['zone_label']}")
    print(f"Urban Stress Index: {row['urban_stress_index']:.1f}/100")

    # --- PLANNING RECOMMENDATIONS ENGINE ---
    print(">> Urban Planning Actions:")

    # Rule 1: Stagnation Zone (Low Wind, High Pollution)
    if row['zone_label'] == "Stagnation Zone (High Risk)":
        print("   - CONSTRUCTION: Enforce strict dust mitigation laws.")
        print("   - INFRASTRUCTURE: Mandate 'Ventilation Corridors' in building codes.")
        print("   - ALERT: Priority zone for Smog Towers installation.")

    # Rule 2: Traffic Hotspot (High NO2, High CO)
    elif row['zone_label'] == "Traffic Hotspot (Emission Source)":
        print("   - TRAFFIC: Implement Odd-Even or Congestion Pricing.")
        print("   - GREEN: Develop vertical gardens on road dividers.")
        print("   - TRANSIT: Prioritize EV charging station deployment.")

    # Rule 3: Heat/General Stress
    if row['urban_stress_index'] > 50:
        print("   - WATER: Identify sites for rainwater harvesting to combat heat.")

    print("-" * 40)

# ==========================================
# VISUALIZATION: ZONE MAPPING
# ==========================================

plt.figure(figsize=(10, 6))
plt.scatter(location_stats['lon'], location_stats['lat'],
            c=location_stats['urban_stress_index'], cmap='RdYlGn_r',
            s=200, edgecolors='black', linewidth=1)

# Annotate points
for i, row in location_stats.iterrows():
    plt.text(row['lon']+0.01, row['lat'], row['location'], fontsize=9)

plt.colorbar(label='Urban Stress Index (0=Healthy, 100=Critical)')
plt.title('Urban Metabolism Map: City Stress & Vulnerability Zones')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.grid(True)
plt.show()

print("\nUrban Planning Analysis Complete.")